# Generated by Django 5.1.5 on 2025-01-21 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=250)),
                ('Images', models.ImageField(upload_to='Slider')),
                ('Date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
