# Generated by Django 5.1.5 on 2025-01-24 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Catagory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titel', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='Blog/')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('discription', models.TextField()),
                ('tag', models.TextField(blank=True, null=True)),
                ('catagory', models.ManyToManyField(to='Blog.catagory')),
            ],
        ),
    ]
