# Generated by Django 5.1.5 on 2025-01-24 04:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0002_catagory_blogpost'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogViewrs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('view', models.PositiveIntegerField(default='0')),
                ('blogpost', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Blog.blogpost')),
            ],
        ),
    ]
